version: "3.5"

services:
  app:
    image: node:15-alpine
    container_name: seedsinspace
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"
    working_dir: /usr/app
    command:
      - /bin/sh
      - -c
      - |
        npm install --verbose
        npm start
    stdin_open: true
    tty: true
